const standardSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VisitRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon1.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon2.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon3.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_ResideRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_RomanceRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_MasterRomanceRibbon.PNG?raw=true'
];

const sourSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VisitRibbon.PNG?raw=true'
];

const petSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon1.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon2.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VariantRibbon3.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_ResideRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_RomanceRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_MasterRomanceRibbon.PNG?raw=true'
];

const scotchSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_ResideRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_RomanceRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_MasterRomanceRibbon.PNG?raw=true'
];

const whiteScotchSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_VisitRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_ResideRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_RomanceRibbon.PNG?raw=true',
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_MasterRomanceRibbon.PNG?raw=true'
];

const plantSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_PlantRibbon.PNG?raw=true'
];

const tinkerSet = [
    'https://github.com/IciStorm/VPBingo/blob/main/images/awards/UI_Icon_Charactor_Bart.PNG?raw=true'
];

const validCombos = {
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Arocknid.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Badgesicie.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Barkbark.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Bonboon.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Bunnycomb.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Buzzenge.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Buzzlegum.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Candary.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Chewnicorn.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Chippopotamus.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Cinnamonkey.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Cluckles.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Cocoadile.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Crowla.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Doenut.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Dragumfly.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Eaglair.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Elephanilla.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Fizzlybear.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Black.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Blue.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Brown.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Green.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Orange.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Pink.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Purple.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Red.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_White.PNG?raw=true' : whiteScotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Flutterscotch_Yellow.PNG?raw=true' : scotchSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Fourheads.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Fudgehog.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Galagoogoo.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Goobaa.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Horstachio.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Jameleon.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Juicygoose.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Kittyfloss.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Lackatoad.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Lickatoad.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Macaracoon.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Mallowolf.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Moozipan.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Mothdrop.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Mousemallow.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Newtgat.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Ponocky.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Parrybo.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Pigxie.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Preztail.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Profitamole.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Pudgeon.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Quackberry.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Raisant.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Rashberry.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Reddhott.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Roario.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Salamango.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Shellybean.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sherbat.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Bonboon.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Crowla.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Cocoadile.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Macaracoon.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Mallowolf.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Profitamole.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Shellybean.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sour_Sherbat.PNG?raw=true' : sourSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sparrowmint.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Squazzil.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Swanana.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Sweetooth.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Syrupent.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Taffly.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Twingersnap.PNG?raw=true' : petSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Whirlm.PNG?raw=true' : standardSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/UI_Icon_Pinata_Zumbug.PNG?raw=true' : petSet,

    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Apple.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Banana.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/BirdOfParadise.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Blackberry.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Bluebell.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Bullrush.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Buttercup.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Carrot.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Chili.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Corn.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Daisy.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Fir.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Gem.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Gooseberry.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Hazelnut.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Monkeynut.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Nightshade.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Oak.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Orchid.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/PoisonIvy.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Poppy.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Pumpkin.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Snapdragon.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Sunflower.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Thistle.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Toadstool.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Tulip.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Turnip.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/VenusPinataTrap.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/WaterLily.PNG?raw=true' : plantSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Plants/Watercress.PNG?raw=true' : plantSet,

    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Acorn.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Apple.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Banana.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Blackberry.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Bread.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Bone.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Carrot.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Chili.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Corn.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Fir.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Gem.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Gooseberry.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Hazelnut.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Honey.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Milk.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Monkeynut.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Nightshade.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Pumpkin.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Turnip.PNG?raw=true' : tinkerSet,
    'https://github.com/IciStorm/VPBingo/blob/main/images/Tinkerables/Wool.PNG?raw=true' : tinkerSet
};
